### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by Irirwanirira** [UsirusenIkon/To-Do-List#3]
Hi [@UsirusenIkon ],

Good job so far on your project, you put in much effort to work on this project and that is highly commendable.
However, there are a few suggestions I would like you to implement to make your project look professional;

- [ ] Structure your project by creating folders containing the sections, e.g. images, and the result folder.
- [ ] Update on HTML semantic usage. This will provide easy project navigation.
- [ ] Please Update the Live Demo of the project, your link seems to be broken.

Happy coding!!

**Comment by UsirusenIkon** [comment]
Thanks for the input
